- name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          "scripts": {
   "deploy": "nx run share-a-meal-web:build",
    "build": "nx run-many -t build",
    "test": "nx run-many -t test"
},
- name: Zip artifacts for deployment
  run: |
    echo ${GITHUB_WORKSPACE}
    cd ${GITHUB_WORKSPACE}/dist/apps/backend-api/ && zip ${GITHUB_WORKSPACE}/backend-api-release.zip ./* -r
    cd ${GITHUB_WORKSPACE}/dist/apps/frontend-app/ && zip ${GITHUB_WORKSPACE}/frontend-app-release.zip ./* -r
    - name: Upload share-a-mail-web artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: app-frontend.
          path: frontend-app-release.zip
          
- name: Upload data-api artifact for deployment job
  uses: actions/upload-artifact@v3
  with:
    name: node-app-backend
    path: backend-api-release.zip
    deploy-data-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app-backend

      - name: Unzip artifact for deployment
        run: unzip backend-api-release.zip

      - name: Install dependencies
              run: npm install
       
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NxWorkshop'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: .
